# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c27b05c6801aaf16bf603464c77e67f88c515908a791d195af4d8534695d68f40d73203ee835541b9b912574d0e74dc5d9432bfd2a52108d2a6544423f42775

test:
  secret_key_base: 3d9901baa8fc119c76760b9d012f3b058b50ae710ebfea9bcc0db032e1ab59bddd9fe0a19c024a07ec41fa1929290333ac0d5a573866366aec11d5b0ec2458a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
